version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: taxi-grand-app
    container_name: taxi-grand-app
    restart: unless-stopped
    working_dir: /var/www/html
    environment:
      - APP_ENV=local
      - APP_KEY=${APP_KEY}
      - DB_HOST=mysql
      - DB_PORT=3307
      - DB_DATABASE=taxi_grand
      - DB_USERNAME=root
      - DB_PASSWORD=
      - REDIS_HOST=redis
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
      - ./vendor:/var/www/html/vendor
    networks:
      - taxi-network
    depends_on:
      - mysql
      - redis

  nginx:
    image: nginx:alpine
    container_name: taxi-grand-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - taxi-network
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: taxi-grand-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: taxi_grand
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"
    command:
      - --port=3307
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - taxi-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-P", "3307"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: taxi-grand-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - taxi-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: taxi-grand-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3307
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - "8081:80"
    networks:
      - taxi-network
    depends_on:
      - mysql

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local

networks:
  taxi-network:
    driver: bridge
